# NUMPY

In [7]:
# numerical python
# 고성능 수치 계산을 위한 라이브러리
# 벡터나 행렬 연산에 편리한 기능 제공
# 모든 원소는 같은 자료형만 가능

In [15]:
import numpy as np
# 호출한 함수는 'arange'는 리턴을 하는데 반드시 자기 자리로 돌아온다. 
a = np.arange( 15 ) ## 1차원 데이터 
print(a)
## 다시 차원을 바꾸겠다 'reshape'
a = a.reshape( 3, 5 )
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [55]:
import numpy as np
a = np.arange(15)
print(a)
a = a.reshape(3,5, order = F)
print(a)
print(type(a))
print(a.shape) # 함수가 아니라, 변수임 'shape 차원'
print(a.dtype)
print(a.ndim) # 2차원 데이터
print(a.size)


# print(dir(np))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>
(3, 5)
int32
2
15


In [57]:
#비정형 데이터 => 길이, 리스트 등이 정해져있지않은것
## 그래서 비정형 데이터를 가져오면 지저분한 경우가 많음 
### 그러므로 데이터를 가져올 때, '몇 차원 데이터인지', '데이터가 어떻게 배열되어있는지' 확인하는 것이 좋다. 
#함수마다 사용법이 다르다. 매개변수를 안 두고 쓰는 경우가 있고 없는 경우도 있다. 
# 라이브러리에 무슨 내용이 들어있는지 확인할 수 있다. 

In [61]:
print(a) # 모든 셀을 실행해라

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [115]:
b = np.array( [-1, 2, 5, -3, 0, 5, 7, -9, 7, -4, -7]) #List
print(type(b))
b = np.array(b)
print(type(b))

t = (10, 20, 30, 40, 50) # Tuple
print(type(t))
t = np.array(t)
print(type(t))
#딕셔너리는 numpy로 바꿀 수 없다. 딕셔너리는 값이 key, value 2개이기 때문이다. 딕셔너리는 pandas와 호환이 된다. 

s = (10, 20, 30, 40, 50) #Set
print(type(s))
s = np.array(s)
print(type(s))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'tuple'>
<class 'numpy.ndarray'>


In [93]:
print(b.shape)
print(b.ndim)
print(b.dtype)
print(b)

#print(help(np))

(11,)
1
int32
[-1  2  5 -3  0  5  7 -9  7 -4 -7]


In [105]:
print(np.abs(b)) #절대값
#print(np.sqrt(b)) # nan 은 결과를 못 낸다는 의미
print(np.sqrt(np.abs(b))) #제곱근
print(np.square(b)) # 제곱

[1 2 5 3 0 5 7 9 7 4 7]
[1.         1.41421356 2.23606798 1.73205081 0.         2.23606798
 2.64575131 3.         2.64575131 2.         2.64575131]
[ 1  4 25  9  0 25 49 81 49 16 49]


In [133]:
print(np.isnan(b)) # nan 여부
print(np.sum(b)) #합계
print(np.mean(b)) # 평균
print(np.max(b)) # 최대값 
print(np.min(b)) # 최소값
print(np.argmax(b)) # 최대값 인덱스
print(np.argmin(b)) # 최소값 인덱스

[False False False False False False False False False False False]
2
0.18181818181818182
7
-9
6
7


In [141]:
print(np.sort(b)) #정렬 오름차순
# print(np.sort(b)) # 오름차순된 데이터를 거꾸로 만들어라
print(np.sort(b)[::-1]) #정렬 내림차순 
# 전체 데이터 중에서 일부만 꺼낼때, [start : end : step] 시작 : 끝 : 간격 인덱스

[-9 -7 -4 -3 -1  0  2  5  5  7  7]
[ 7  7  5  5  2  0 -1 -3 -4 -7 -9]


In [143]:
print(np.median(b)) # 중간값

0.0
